let MainSlide = [
  { id: 1, title: "تجربه غذای سالم و گیاهی به سبک ترخینه", img: "/images/slider/slide1.jpg" },
  {
    id: 2,
    title: "رستوران ما با محیط دلنشین و دکوراسیون زیبا شما را پذیرایی می‌کند",
    img: "/images/slider/slide2.jpg",
  },
  { id: 3, title: "خدمات حرفه‌ای و مهمان‌نواز در رستوران ما", img: "/images/slider/slide3.jpg" },
  { id: 4, title: "غذاهای تازه و با کیفیت بالا را در رستوران ما پیدا کنید", img: "/images/slider/slide4.jpg" },
  { id: 5, title: "تجربهٔ غذاهای لذیذ را در رستوران ما تجربه کنید", img: "/images/slider/slide5.jpg" },
];

let MainMenu = [
  {
    id: 1,
    title: "نوشیدنی",
    src: "/menu",
    img: "images/Mainmenu/image.png",
  },
  {
    id: 2,
    title: "دسر",
    src: "/menu",
    img: "images/Mainmenu/image-1.png",
  },
  {
    id: 3,
    title: "پیش غذا",
    src: "/menu",
    img: "images/Mainmenu/image-2.png",
  },
  {
    id: 4,
    title: "غذای اصلی",
    src: "/menu",
    img: "images/Mainmenu/image-3.png",
  },
];

let Branches = [
  {
    id: "ekbatan",
    title: "اکباتان",
    adress: "شهرک اکباتان، فاز ۳، مجتمع تجاری کوروش، طبقه سوم",
    images: [
      "images/branches/ekbatan/ekbatan (1).jpg",
      "images/branches/ekbatan/ekbatan (2).jpg",
      "images/branches/ekbatan/ekbatan (3).jpg",
      "images/branches/ekbatan/ekbatan (4).jpg",
      "images/branches/ekbatan/ekbatan (5).jpg",
    ],
  },
  {
    id: "chalous",
    title: "چالوس",
    adress: "چالوس، خیابان ۱۷ شهریور، بعد کوچه کوروش، جنب داروخانه دکتر میلانی",
    images: [
      "images/branches/chalous/chalous (1).jpg",
      "images/branches/chalous/chalous (2).jpg",
      "images/branches/chalous/chalous (3).jpg",
      "images/branches/chalous/chalous (4).jpg",
      "images/branches/chalous/chalous (5).jpg",
    ],
  },
  {
    id: "aghdasieh",
    title: "اقدسیه",
    adress: "خیابان اقدسیه ، نرسیده به میدان خیام، پلاک ۸",
    images: [
      "images/branches/aghdasieh/aghdasieh (1).jpg",
      "images/branches/aghdasieh/aghdasieh (2).jpg",
      "images/branches/aghdasieh/aghdasieh (3).jpg",
      "images/branches/aghdasieh/aghdasieh (4).jpg",
      "images/branches/aghdasieh/aghdasieh (5).jpg",
    ],
  },
  {
    id: "vanak",
    title: "ونک",
    adress: "میدان ونک، خیابان فردوسی، نبش کوچه نیلوفر، پلاک ۲۶",
    images: [
      "images/branches/vanak/vanak (1).jpg",
      "images/branches/vanak/vanak (2).jpg",
      "images/branches/vanak/vanak (3).jpg",
      "images/branches/vanak/vanak (4).jpg",
      "images/branches/vanak/vanak (5).jpg",
    ],
  },
];

let MainFoods = [
  {
    id: 1,
    name: "کوفته برنجی",
    ingredients: "برنج سبزی کوفته لپه آرد نخودچی، گردو و زرشک و آلو پیاز",
    price: 180_000,
    off: 35,
    category: "غذاهای ایرانی",
    img: "/images/persianfood/persianfood-2.png",
    specialOffer: true,
    rating: 5,
    votes: 52,
    ekbatan: true,
    chalous: true,
    vanak: false,
    aghdasieh: false,
  },
  {
    id: 2,
    name: "کشک بادمجان",
    ingredients: "بادمجان، کشک، نعناع خشک، مغز گردو، سیر، پیاز",
    price: 95_000,
    off: 0,
    category: "غذاهای ایرانی",
    img: "/images/persianfood/persianfood-1.png",
    specialOffer: true,
    rating: 3,
    votes: 52,
    ekbatan: true,
    chalous: false,
    vanak: true,
    aghdasieh: true,
  },
  {
    id: 3,
    name: "میرزا قاسمی",
    ingredients: "بادمجان، گوجه فرنگی، تخم مرغ، سیر، رب گوجه فرنگی",
    price: 165_000,
    off: 10,
    category: "غذاهای ایرانی",
    img: "/images/persianfood/persianfood-4.png",
    specialOffer: true,
    rating: 5,
    votes: 52,
    ekbatan: true,
    chalous: false,
    vanak: true,
    aghdasieh: false,
  },
  {
    id: 4,
    name: "باقلاقاتوق ",
    ingredients: " پاچ باقلا، شوید خشک، کره، سیر، تخم مرغ",
    price: 205_000,
    off: 30,
    category: "غذاهای ایرانی",
    img: "/images/persianfood/persianfood-3.png",
    specialOffer: true,
    rating: 2,
    votes: 52,
    ekbatan: true,
    chalous: false,
    vanak: true,
    aghdasieh: true,
  },
  {
    id: 5,
    name: "فلافل ",
    ingredients: " نخود، پیاز، تخم گشنیز، سیر، جعفری، سیب زمینی",
    price: 80_000,
    off: 0,
    category: "غذاهای ایرانی",
    img: "/images/persianfood/persianfood-6.png",
    specialOffer: false,
    rating: 4,
    votes: 52,
    ekbatan: true,
    chalous: false,
    vanak: true,
    aghdasieh: true,
  },
  {
    id: 6,
    name: "کله جوش ",
    ingredients: "شک، گردو، پیاز، نعناع خشک ",
    price: 180_000,
    off: 35,
    category: "غذاهای ایرانی",
    img: "/images/persianfood/persianfood-5.png",
    specialOffer: true,
    rating: 2,
    votes: 52,
    ekbatan: true,
    chalous: true,
    vanak: true,
    aghdasieh: false,
  },
  {
    id: 7,
    name: " asda",
    ingredients: "asdasd ",
    price: 180_000,
    off: 35,
    category: " غذاهای غیر ایرانی",
    img: "/images/persianfood-2.png",
    specialOffer: false,
    rating: 1,
    votes: 52,
    ekbatan: true,
    chalous: false,
    vanak: true,
    aghdasieh: false,
  },
  {
    id: 8,
    name: " asdasd",
    ingredients: "asdasd ",
    price: 180_000,
    off: 35,
    category: "پیتزاها ",
    img: "/images/persianfood-2.png",
    specialOffer: true,
    rating: 1,
    votes: 52,
    ekbatan: true,
    chalous: false,
    vanak: true,
    aghdasieh: true,
  },
  {
    id: 9,
    name: " asdasd",
    ingredients: "asdasd ",
    price: 180_000,
    off: 35,
    category: "ساندویچ‌ها ",
    img: "/images/persianfood-2.png",
    specialOffer: false,
    rating: 5,
    votes: 52,
    ekbatan: true,
    chalous: false,
    vanak: true,
    aghdasieh: true,
  },
];

export { MainSlide, Branches, MainMenu, MainFoods };
